export default {
  PLAYERS_PER_PAGE: 25,
  SKILLS: [
    "attack",
    "defence",
    "strength",
    "constitution",
    "ranged",
    "prayer",
    "magic",
    "cooking",
    "woodcutting",
    "fletching",
    "fishing",
    "firemaking",
    "crafting",
    "smithing",
    "mining",
    "herblore",
    "agility",
    "thieving",
    "slayer",
    "farming",
    "runecrafting",
    "skiller",
    "hunter",
    "summoning",
    "dungeoneering",
  ],
  STATS: {
    total_xp: "Total Experience",
    bonus_prestiges: "Bonus Prestiges",
    total_boss_kills: "Total Boss Kills",
    completed_clogs: "Completed Collection Logs",
    achievement_points: "Achievement Points",
    slayer_tasks: "Total Slayer Tasks",
    skiller_tasks: "Total Skiller Tasks",
    crystal_chests: "Crystal Chests",
    rare_candies: "Rare Candy Used",
    wilderness_kills: "Wilderness Kills",
    wilderness_deaths: "Wilderness Deaths",
    clue_scrolls_easy: "Clue Scrolls (easy)",
    clue_scrolls_medium: "Clue Scrolls (medium)",
    clue_scrolls_hard: "Clue Scrolls (hard)",
    clue_scrolls_elite: "Clue Scrolls (elite)",
    clue_scrolls_master: "Clue Scrolls (master)"
  },
  BOSSES: {
    cox: "Chambers of Xeric",
    tob: "Theatre of Blood",
    gwdraid: "GWD Raid",
    chaos: "Chaos Raid",
    barrows: "Barrows Raid",
    superior_slayer: "Superior Slayer", //bosses
    dagannoth_supreme: "Dagannoth Supreme",
    dagannoth_prime: "Dagannoth Prime",
    dagannoth_rex: "Dagannoth Rex",
    king_black_dragon: "King Black Dragon",
    cerberus: "Cerberus",
    kril_tsutsaroth: "K'ril Tsutsaroth",
    kreearra: "Kree'arra",
    commander_zilyana: "Commander Zilyana",
    general_graardor: "General Graardor",
    corporeal_beast: "Corporeal Beast",
    abyssal_sire: "Abyssal Sire",
    tormented_demon: "Tormented Demon",
    zulrah: "Zulrah",
    kalphite_queen: "Kalphite Queen",
    glacio: "Glacio",
    wildywyrm: "WildyWyrm",
    giant_mole: "Giant Mole",
    thermonuclear_smoke_devil: "Thermonuclear Smoke Devil",
    nightmare: "Nightmare",
    tztok_jad: "TzTok-Jad",
    venenatis: "Venenatis", //wildy
    chaos_elemental: "Chaos Elemental",
    scorpia: "Scorpia",
    vetion: "Vet'ion",
    callisto: "Callisto",
    vorkath: "Vorkath",
    revenant_dark_beast: "Revenant Dark Beast",
    revenant_ork: "Revenant Ork",
    revenant_werewolf: "Revenant Werewolf",
    revenant_goblin: "Revenant Goblin",
    revenant_impling: "Revenant Impling",
  },
};
